[package]
name = "inky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
rppal = "0.14.1"
